name: Super-Linter Test

on:
  push:
    branches:
      - master
      - main

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: ""
      
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
